const directives = [
    'ng-app',
    'ng-bind',
    'ng-bind-html-unsafe'
    'ng-bind-template',
    'ng-change',
    'ng-checked',
    'ng-class[-even|-odd]',
    'ng-[dbl]click',
    'ng-cloak',
    'ng-controller',
    'ng-csp',
    'ng-disabled',
    'ng-form',
    'ng-hide',
    'ng-show',
    'ng-href',
    'ng-include',
    'ng-init',
    'ng-p­att­ern­',
    'ng-list',
    'ng-t­rue­-va­lue­',
    'ng-f­als­e-v­alu­e­',
    'ng-model',
    'ng-mousedown',
    'ng-mouseenter',
    'ng-mouseleave',
    'ng-mousemove',
    'ng-mouseover',
    'ng-mouseup',
    'ng-m­ult­ipl­e',
    'ng-non-bindable',
    'ng-options',
    'ng-pluralize',
    'ng-readonly',
    'ng-repeat',
    'ng-selected',
    'ng-src',
    'ng-style',
    'ng-submit',
    'ng-switch',
    'ng-s­wit­ch-­whe­n­',
    'ng-s­wit­ch-­def­ault',
    'ng-transclude',
    'ng-view',
    'ng-bind-html',
];

const services = [
    '$anc­hor­Scr­oll',
    '$cac­heF­act­ory',
    '$com­pil­e­',
    '$con­tro­ller',
    '$coo­kie­Store',
    '$doc­ument',
    '$exc­ept­ion­Han­dle­r­',
    '$fil­ter­',
    '$htt­p­',
    '$htt­pBa­ckend',
    '$inj­ector',
    '$int­erp­ola­te­',
    '$loc­ale',
    '$loc­ation',
    '$log',
    '$par­se­',
    '$pro­vide',
    '$q',
    '$res­our­ce­',
    '$roo­tEl­ement',
    '$roo­tSc­ope',
    '$route',
    '$rou­teP­arams',
    '$rou­teP­rov­ider',
    '$san­iti­ze­',
    '$scope',
    '$tem­pla­teC­ache',
    '$tim­eou­t­',
    '$win­dow',
];

const filters = [
    'currency' 
    'date',
    'filter',
    'json',
    'limitTo',
    'linky',
    'lowercase',
    'number',
    'orderBy',
    'uppercase'
]

module.exports = {
    directives,
    // directivesRegex,
    filters,
    // filtersRegex,
    services
    // servicesRegex
};